# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0004_auto_20170408_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('correct_answer', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('response', models.CharField(choices=[('NR', 'no response'), ('IC', 'incorrect'), ('CR', 'correct')], default='NR', max_length=2)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
