# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170520_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='entry',
        ),
    ]
