# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequency',
            old_name='frequncy',
            new_name='frequency',
        ),
    ]
