# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20170423_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SingleCounts',
            new_name='MultiCount',
        ),
        migrations.RenameModel(
            old_name='MultiCounts',
            new_name='SingleCount',
        ),
    ]
