# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multicount',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='singlecount',
            name='entry',
        ),
        migrations.DeleteModel(
            name='MultiCount',
        ),
        migrations.DeleteModel(
            name='SingleCount',
        ),
    ]
