# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.CharField(max_length=100)),
                ('traditional', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Entry'),
        ),
    ]
