# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20170330_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='entry',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='order',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='pronunciation',
            new_name='pin_yin',
        ),
        migrations.AddField(
            model_name='entry',
            name='definition',
            field=models.TextField(default='definition'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Definition',
        ),
    ]
