# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20170328_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='simple',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
