# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20170408_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='definition',
            new_name='definitions',
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
